### ISSUE TITLE
Is there a way to ignore specific directories?

### ISSUE THREAD

**Issue by YaManicKill** [sailsjs/sails-build-dictionary#3]
So, I have angular2 in my node_modules, and it's causing this error from build-dictionary:
```
> porybox@0.0.1 start /home/al/dev/porybox
> node app.js

module.js:433
    throw err;
    ^

SyntaxError: /home/al/dev/porybox/node_modules/angular2/ts/package.json: Unexpected token <
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at /usr/lib/node_modules/sails/node_modules/include-all/index.js:54:23

npm ERR! Linux 4.2.8-200.fc22.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! porybox@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the porybox@0.0.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the porybox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs porybox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls porybox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/al/dev/porybox/npm-debug.log
```

The package.json appears to be an ejs template rather than a package.json. So, is there a way to exclude this specific module, because obviously I know it isn't a sails hook.

**Comment by sgress454** [comment]
> The package.json appears to be an ejs template rather than a package.json.

:-1: x :100: 

If you're not using any installable hooks, the easiest thing by far would be to just turn off the `userhooks` module in your `.sailsrc` file:

```
"hooks": {
  "userhooks": false
}
```

**Comment by sgress454** [comment]
Closing this issue in favor of https://github.com/balderdashy/sails/issues/3639

**Comment by sgress454** [comment]
(also pushed up a patch, you can try it in your project w/ `npm install https://github.com/balderdashy/sails.git`)

**Comment by YaManicKill** [comment]
Sorry, I ended up using angular 1 instead, as there were other issues I had with angular 2, so I am not able to test this.
